version: "3.0"
services:
  client:
    container_name: z26_z11_client
    build: ./client
    tty: true
    cap_add:
    - NET_ADMIN
  server:
    container_name: z26_z11_server
    build: ./server
    tty: true
    cap_add:
    - NET_ADMIN
